import"./assets/shopping-list-help-df111c88.js";import{i as w,g as S,a as r,b as c,S as L}from"./assets/vendor-e9ea2541.js";const B={apiKey:"AIzaSyD8UvisVnkCvMijmf6q4ZtLkQgC43vz2KM",authDomain:"dookshelf-357a4.firebaseapp.com",projectId:"dookshelf-357a4",storageBucket:"dookshelf-357a4.appspot.com",messagingSenderId:"957443484270",appId:"1:957443484270:web:de06245395594e6cf9947f",measurementId:"G-PGZE6HZC47"};w(B);S();const p=document.querySelector(".Form-window"),E=document.querySelector(".Close-form-btn"),C=document.querySelector(".header-user");document.getElementById("email");document.getElementById("password");document.getElementById("username");document.querySelector(".form__btn");document.querySelector(".form__btn-up");document.querySelector(".form__btn-in");C.addEventListener("click",function(){p.classList.add("is-open")});E.addEventListener("click",function(){p.classList.remove("is-open")});function x(){const e=document.getElementById("burgerToggle"),t=document.getElementById("burgerMenu");e.addEventListener("click",function(){t.classList.toggle("burger-menu-show"),t.classList.contains("burger-menu-show")?e.innerHTML=`
        <svg width="18" height="18" stroke="#000">
          <use href="./images/icons/symbol-defs.svg#icon-close"></use>
        </svg>`:e.innerHTML=`
        <svg width="28" height="28">
          <use href="./images/icons/symbol-defs.svg#icon-menu"></use>
        </svg>`})}document.addEventListener("DOMContentLoaded",function(){x()});const T=document.getElementById("home");document.getElementById("shopping-list");T.classList.add("active");const l=document.querySelector(".list-one"),f=document.querySelector(".list_categories"),a=document.querySelector(".main-title");let d;function q(){let e=window.innerWidth;return e<=767?0:e<=1439?2:4}function h(){const e=a.textContent.split(" "),t=e[e.length-1];a.innerHTML=a.innerHTML.replace(t,`<span class="blue">${t}</span>`)}async function b(){new L(".link-img")}async function y(e){l.innerHTML="";let t="";const s=q();for(let n in e){t+=`
            <li class="books_list">
                <h2 class="name_category">${e[n].list_name}</h2>
                <ul class="images_books">`;for(let o in e[n].books)if(t+=`<li class="image_book" data-category="${e[n].books[o]._id}">
                                    <div class="div-animation">
                                            <a class="link-img" href="${e[n].books[o].book_image}"><img class="img-example" alt="Book title" src="${e[n].books[o].book_image}"></img></a>
                                        <div class="box-quick-view"><p class="animation-paragraf">Quick view</p></div>
                                    </div>
                                
                                <div class="box-cards">
                                    <p class="title-book">${e[n].books[o].title}</p>
                                    <p class="author-book">${e[n].books[o].author}</p>
                                </div>
                            </li>`,s==o)break;t+=`</ul><button class="button-see-more" data-category="${e[n].list_name}">See more</button></li>`}l.insertAdjacentHTML("beforeend",t),b()}l.addEventListener("click",async e=>{if(e.target.classList.contains("button-see-more")){const t=e.target.dataset.category;a.textContent=t;const s=a.textContent.split(" "),n=s[s.length-1];a.innerHTML=a.innerHTML.replace(n,`<span class="blue">${n}</span>`),await r.get(`https://books-backend.p.goit.global/books/category?category=${t}`).then(o=>{if(o.data.length===0)throw new Error("Sorry, books in the selected category were not found");k(o.data)}).catch(o=>c.error({title:"Error",message:o.message}))}});async function M(){l.innerHTML="",a.textContent==="Best Sellers Books"?await r.get("https://books-backend.p.goit.global/books/top-books").then(e=>{if(e.data.length===0)throw new Error("Sorry, books in the selected category were not found");y(e.data)}).catch(e=>c.error({title:"Error",message:e.message})):await r.get(`https://books-backend.p.goit.global/books/category?category=${d}`).then(e=>{if(e.data.length===0)throw new Error("Sorry, books in the selected category were not found");k(e.data)}).catch(e=>c.error({title:"Error",message:e.message}))}M();async function _(e){let t="";const s='<li tabindex="0" class="categoria">All categories</li>';e.forEach(o=>{t+=`<li tabindex="0" class="categoria">${o.list_name}</li>`}),f.insertAdjacentHTML("beforeend",t),f.insertAdjacentHTML("afterbegin",s),document.querySelectorAll(".categoria").forEach(o=>{o.addEventListener("click",async g=>{g.preventDefault(),d=g.target.textContent,d=d.replace(/ /g,"%20"),g.target.textContent!=="All categories"?(a.textContent=g.target.textContent,h(),await r.get(`https://books-backend.p.goit.global/books/category?category=${d}`).then(i=>{if(i.data.length===0)throw new Error("Sorry, books in the selected category were not found");k(i.data)}).catch(i=>c.error({title:"Error",message:i.message}))):(a.textContent="Best Sellers Books",h(),await r.get("https://books-backend.p.goit.global/books/top-books").then(i=>{if(i.data.length===0)throw new Error("Sorry, books in the selected category were not found");y(i.data)}).catch(i=>c.error({title:"Error",message:i.message})))})})}r.get("https://books-backend.p.goit.global/books/category-list").then(e=>{_(e.data)}).catch(e=>c.error({title:"Error",message:e.message}));async function k(e){let t="";l.innerHTML="",e.forEach(s=>{t+=`<li class="book" data-category="${s._id}">
                        <div class="div-animation">
                        <a class="link-img" href="${s.book_image}"><img class="img-example" alt="Book title" src="${s.book_image}"></img></a>
                            <div class="box-quick-view"><p class="animation-paragraf">Quick view</p></div>
                        </div>
                                <div class="box-cards">
                                    <p class="title-book">${s.title}</p>
                                    <p class="author-book">${s.author}</p>
                                </div>
                      </li>`}),l.insertAdjacentHTML("beforeend",t),b()}document.querySelector(".img-example");document.querySelector(".content-title");document.querySelector(".content-descr");document.querySelector(".modal-descr");document.querySelector(".amazon");document.querySelector(".apple");const m=document.querySelector("#add"),v=document.querySelector(".hidden-information");m.addEventListener("click",I);r.defaults.timeout=4e3;function I(e){const t=e.target.attributes.id.value;m.textContent==="Add to shopping list"?$(t):H(t)}function $(e){let t=localStorage.getItem("idBooks");(t==="undefined"||!t||t==="")&&(t=[],localStorage.setItem("idBooks",JSON.stringify(t)),t=JSON.parse(localStorage.getItem("idBooks")),t.push(e),localStorage.setItem("idBooks",JSON.stringify(t)),m.textContent="Remove from shopping list",v.classList.remove("visually-hidden"))}function H(e){let t=JSON.parse(localStorage.getItem("idBooks"));t.splice(t.indexOf(e),1),localStorage.setItem("idBooks",JSON.stringify(t)),m.textContent="Add to shopping list",v.classList.add("visually-hidden")}const u=document.querySelector(".scrollToTop");window.onscroll=()=>{window.scrollY>500?u.classList.remove("isHide"):window.scrollY<500&&u.classList.add("isHide"),u.onclick=()=>{window.scrollTo(0,0)}};
//# sourceMappingURL=commonHelpers.js.map
